BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[chats] (
    [id] NVARCHAR(1000) NOT NULL,
    [threadsId] NVARCHAR(1000) NOT NULL,
    [userProfileId] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [chats_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [chats_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[chats] ADD CONSTRAINT [chats_userProfileId_fkey] FOREIGN KEY ([userProfileId]) REFERENCES [dbo].[user_profiles]([id]) ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
